/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiSelectSelect: typeof import('./../../src/components/ui/select/Select.vue')['default']
    UiSelectSelectContent: typeof import('./../../src/components/ui/select/SelectContent.vue')['default']
    UiSelectSelectGroup: typeof import('./../../src/components/ui/select/SelectGroup.vue')['default']
    UiSelectSelectItem: typeof import('./../../src/components/ui/select/SelectItem.vue')['default']
    UiSelectSelectItemText: typeof import('./../../src/components/ui/select/SelectItemText.vue')['default']
    UiSelectSelectLabel: typeof import('./../../src/components/ui/select/SelectLabel.vue')['default']
    UiSelectSelectScrollDownButton: typeof import('./../../src/components/ui/select/SelectScrollDownButton.vue')['default']
    UiSelectSelectScrollUpButton: typeof import('./../../src/components/ui/select/SelectScrollUpButton.vue')['default']
    UiSelectSelectSeparator: typeof import('./../../src/components/ui/select/SelectSeparator.vue')['default']
    UiSelectSelectTrigger: typeof import('./../../src/components/ui/select/SelectTrigger.vue')['default']
    UiSelectSelectValue: typeof import('./../../src/components/ui/select/SelectValue.vue')['default']
  }
}

// For TSX support
declare global {
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const UiSelectSelect: typeof import('./../../src/components/ui/select/Select.vue')['default']
  const UiSelectSelectContent: typeof import('./../../src/components/ui/select/SelectContent.vue')['default']
  const UiSelectSelectGroup: typeof import('./../../src/components/ui/select/SelectGroup.vue')['default']
  const UiSelectSelectItem: typeof import('./../../src/components/ui/select/SelectItem.vue')['default']
  const UiSelectSelectItemText: typeof import('./../../src/components/ui/select/SelectItemText.vue')['default']
  const UiSelectSelectLabel: typeof import('./../../src/components/ui/select/SelectLabel.vue')['default']
  const UiSelectSelectScrollDownButton: typeof import('./../../src/components/ui/select/SelectScrollDownButton.vue')['default']
  const UiSelectSelectScrollUpButton: typeof import('./../../src/components/ui/select/SelectScrollUpButton.vue')['default']
  const UiSelectSelectSeparator: typeof import('./../../src/components/ui/select/SelectSeparator.vue')['default']
  const UiSelectSelectTrigger: typeof import('./../../src/components/ui/select/SelectTrigger.vue')['default']
  const UiSelectSelectValue: typeof import('./../../src/components/ui/select/SelectValue.vue')['default']
}